In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
from keras.layers import Input, Lambda, Dense, Flatten
from keras.models import Model
from keras.applications.resnet50 import ResNet50
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input
from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
import numpy as np
from glob import glob
import matplotlib.pyplot as plt

In [3]:
train_path=r'C:\Users\user\Desktop\Data sets\Dataset\Train'
test_path=r"C:\Users\user\Desktop\Data sets\Dataset\Test"

In [5]:
IMAGE_SIZE=[224,224]

In [6]:
vgg=VGG16(include_top=False,weights='imagenet',input_shape=IMAGE_SIZE+[3])

In [7]:
#don't train existing weights
for layer in vgg.layers:
    layer.trainable=False

In [8]:
folders_train=glob(r'C:\Users\user\Desktop\Data sets\Dataset\Train\*')
folders_test=glob(r"C:\Users\user\Desktop\Data sets\Dataset\Test\*")

In [51]:
folders_test

['C:\\Users\\user\\Desktop\\Data sets\\Dataset\\Test\\Parasite',
 'C:\\Users\\user\\Desktop\\Data sets\\Dataset\\Test\\Uninfected']

In [52]:
folders_train

['C:\\Users\\user\\Desktop\\Data sets\\Dataset\\Train\\Parasite',
 'C:\\Users\\user\\Desktop\\Data sets\\Dataset\\Train\\Uninfected']

In [9]:
x=Flatten()(vgg.output)

In [10]:
prediction=Dense(len(folders_train),activation='sigmoid')(x)

In [11]:
model=Model(inputs=vgg.input,outputs=prediction)

In [12]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [15]:
import keras

In [19]:
model.compile(keras.optimizers.Adam('le-5'),metrics=['accuracy'],loss='categorical_crossentropy')

In [20]:
model.compile(keras.optimizers.Adam(lr=1e-5),metrics=['accuracy'],loss='categorical_crossentropy')

In [21]:
from keras_preprocessing.image import ImageDataGenerator
train_gen=ImageDataGenerator(rescale=1./225,zoom_range=0.2,horizontal_flip=True)
test_gen=ImageDataGenerator(rescale=1./225)

In [22]:
trainig_set=train_gen.flow_from_directory(r"C:\Users\user\Desktop\Data sets\Dataset\Train",
                                         target_size=(224,224),
                                          batch_size = 32,
                                          class_mode='categorical')

Found 416 images belonging to 2 classes.


In [23]:
testing_set=test_gen.flow_from_directory(r"C:\Users\user\Desktop\Data sets\Dataset\Test",
                                         target_size=(224,224),
                                          batch_size = 32,
                                          class_mode='categorical')

Found 134 images belonging to 2 classes.


In [24]:
model.fit_generator(trainig_set,validation_data=testing_set,epochs=12)

Epoch 1/12
13/13 [==============================] - 258s 20s/step - loss: 0.7239 - accuracy: 0.5132 - val_loss: 0.6892 - val_accuracy: 0.5149
Epoch 2/12
13/13 [==============================] - 257s 20s/step - loss: 0.6911 - accuracy: 0.5206 - val_loss: 0.6826 - val_accuracy: 0.5299
Epoch 3/12
13/13 [==============================] - 238s 19s/step - loss: 0.6748 - accuracy: 0.5493 - val_loss: 0.6893 - val_accuracy: 0.5448
Epoch 4/12
13/13 [==============================] - 151s 11s/step - loss: 0.6856 - accuracy: 0.5507 - val_loss: 0.6837 - val_accuracy: 0.5672
Epoch 5/12
13/13 [==============================] - 154s 12s/step - loss: 0.6660 - accuracy: 0.6011 - val_loss: 0.6809 - val_accuracy: 0.5821
Epoch 6/12
13/13 [==============================] - 148s 12s/step - loss: 0.6632 - accuracy: 0.5837 - val_loss: 0.6727 - val_accuracy: 0.5970
Epoch 7/12
13/13 [==============================] - 144s 11s/step - loss: 0.6391 - accuracy: 0.6689 - val_loss: 0.6669 - val_accuracy: 0.6269
Epoch 

In [25]:
# save it as a h5 file
#we are having only two ways to save the model
#a)h5
#b)tf
from tensorflow.keras.models import load_model

model.save('malaria_vgg16.h5')

In [26]:
y_pred = model.predict(testing_set)

In [27]:
y_pred

array([[0.6035846 , 0.407324  ],
       [0.42161626, 0.39218968],
       [0.39316252, 0.49712425],
       [0.41964927, 0.48024637],
       [0.4174919 , 0.55865026],
       [0.5799502 , 0.41847244],
       [0.4722209 , 0.5151761 ],
       [0.5055036 , 0.5202228 ],
       [0.41131562, 0.5418497 ],
       [0.3921907 , 0.48276266],
       [0.41347125, 0.4710643 ],
       [0.52823734, 0.41931158],
       [0.5110577 , 0.4337749 ],
       [0.51810646, 0.46586484],
       [0.47561747, 0.52087325],
       [0.56978893, 0.44743374],
       [0.45333648, 0.52395266],
       [0.40365112, 0.46851122],
       [0.37762374, 0.5562446 ],
       [0.45209774, 0.32142356],
       [0.42104235, 0.5257799 ],
       [0.4712036 , 0.38137788],
       [0.5453269 , 0.50963664],
       [0.47455138, 0.5381732 ],
       [0.46734536, 0.48816466],
       [0.44242737, 0.51062137],
       [0.5833421 , 0.4339199 ],
       [0.53368765, 0.54281175],
       [0.44509104, 0.4505998 ],
       [0.5739959 , 0.5878976 ],
       [0.

In [28]:
y_pred = np.argmax(y_pred, axis=1)

In [29]:
y_pred

array([0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0], dtype=int64)

In [30]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

In [31]:
model=load_model('malaria_vgg16.h5')

In [42]:
img1=image.load_img(r"C:\Users\user\Desktop\Data sets\Dataset\Train\Parasite\nani.png",target_size=(224,224))

In [43]:
x=image.img_to_array(img1)
x

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [44]:
x.shape

(224, 224, 3)

In [45]:

x=x/255

In [46]:
import numpy as np
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape

(1, 224, 224, 3)

In [47]:
model.predict(img_data)

array([[0.29342002, 0.5049118 ]], dtype=float32)

In [48]:
a=np.argmax(model.predict(img_data), axis=1)

In [50]:
a==0


array([False])